[package]
edition.workspace = true
license.workspace = true
name = "ava-core-api"
version.workspace = true

[lib]
doctest = false
name = "ava_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
ava-app-server-protocol = { workspace = true }
ava-arg0 = { workspace = true }
ava-analytics = { workspace = true }
ava-config = { workspace = true }
ava-core = { workspace = true }
ava-extension-api = { workspace = true }
ava-home = { workspace = true }
ava-history = { workspace = true }
ava-image-generation-extension = { workspace = true }
ava-exec-server = { workspace = true }
ava-features = { workspace = true }
ava-login = { workspace = true }
ava-model-provider-info = { workspace = true }
ava-models-manager = { workspace = true }
ava-protocol = { workspace = true }
ava-state = { workspace = true }
ava-utils-absolute-path = { workspace = true }
