[package]
edition.workspace = true
license.workspace = true
name = "ava-connectors-extension"
version.workspace = true

[lib]
name = "ava_connectors_extension"
path = "src/lib.rs"
doctest = false
test = false

[lints]
workspace = true

[dependencies]
ava-connectors = { workspace = true }
ava-core-plugins = { workspace = true }
ava-file-system = { workspace = true }
ava-plugin = { workspace = true }
ava-utils-path-uri = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
