[package]
name = "ava-chatgpt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
ava-connectors = { workspace = true }
ava-core = { workspace = true }
ava-git-utils = { workspace = true }
ava-http-client = { workspace = true }
ava-login = { workspace = true }
ava-model-provider = { workspace = true }
ava-plugin = { workspace = true }
ava-utils-cli = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
ava-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
