[package]
edition.workspace = true
license.workspace = true
name = "ava-memories-read"
version.workspace = true

[lib]
name = "ava_memories_read"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
ava-protocol = { workspace = true }
ava-shell-command = { workspace = true }
ava-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
