# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: bun
    directory: .github/actions/ava
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: cargo
    directories:
      - ava-rs
      - ava-rs/*
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: docker
    directory: ava-cli
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: rust-toolchain
    directory: ava-rs
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
