[package]
edition.workspace = true
license.workspace = true
name = "ava-cloud-tasks-client"
version.workspace = true

[lib]
name = "ava_cloud_tasks_client"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
ava-api = { workspace = true }
ava-backend-client = { workspace = true }
ava-git-utils = { workspace = true }
ava-http-client = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
