// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvaErrorInfo } from "./AvaErrorInfo";
import type { MisalignmentErrorDetails } from "./MisalignmentErrorDetails";

export type TurnError = { message: string, avaErrorInfo: AvaErrorInfo | null, additionalDetails: string | null,
/**
 * Optional public explanation and continuation instruction for a misalignment block.
 */
misalignment: MisalignmentErrorDetails | null, };
