[package]
name = "ava-backend-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
http = { workspace = true }
url = { workspace = true }
ava-backend-openapi-models = { path = "../backend-openapi-models" }
ava-api = { workspace = true }
ava-http-client = { workspace = true }
ava-login = { workspace = true }
ava-model-provider = { workspace = true }
ava-protocol = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
pretty_assertions = "1"
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
