org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC
org.gradle.daemon=false
org.gradle.parallel=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# Built-in Kotlin enabled to suppress KGP warning for firebase_core
android.builtInKotlin=true
