[package]
edition.workspace = true
license.workspace = true
name = "ava-plugin"
version.workspace = true

[lib]
doctest = false
name = "ava_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ava-config = { workspace = true }
ava-protocol = { workspace = true }
ava-utils-absolute-path = { workspace = true }
ava-utils-path-uri = { workspace = true }
ava-utils-plugins = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
