load("//:defs.bzl", "ava_rust_crate")

ava_rust_crate(
    name = "linux-sandbox",
    crate_name = "ava_linux_sandbox",
    extra_binaries = [
        "//ava-rs/bwrap:bwrap",
    ],
    rustc_env_files = select({
        "@platforms//os:linux": ["//ava-rs/bwrap:bwrap-sha256-env"],
        "//conditions:default": [],
    }),
)
