[package]
name = "ava-install-context"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ava_install_context"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
ava-utils-absolute-path = { workspace = true }
ava-utils-home-dir = { workspace = true }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
