[package]
edition.workspace = true
license.workspace = true
name = "ava-attachment-store"
version.workspace = true

[lib]
doctest = false
name = "ava_attachment_store"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
