[package]
name = "ava-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ava-protocol = { workspace = true }
ava-utils-path-uri = { workspace = true }

[dev-dependencies]
ava-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
