load("//:defs.bzl", "ava_rust_crate")

ava_rust_crate(
    name = "v8-poc",
    crate_features = select({
        "@llvm//constraints/windows/abi:msvc": [],
        "//conditions:default": ["sandbox"],
    }),
    crate_name = "ava_v8_poc",
    deps_extra = ["@crates//:v8"],
)

alias(
    name = "v8-poc-rusty-v8",
    actual = ":v8-poc",
)
