[package]
edition.workspace = true
license.workspace = true
name = "ava-context-fragments"
version.workspace = true

[lib]
name = "ava_context_fragments"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
ava-protocol = { workspace = true }
ava-utils-string = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
