[package]
edition.workspace = true
license.workspace = true
name = "ava-features"
version.workspace = true

[lib]
doctest = false
name = "ava_features"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ava-network-proxy = { workspace = true }
ava-otel = { workspace = true }
ava-protocol = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
