[package]
edition.workspace = true
license.workspace = true
name = "ava-browser-extension"
version.workspace = true

[lib]
name = "ava_browser_extension"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
ava-config = { workspace = true }
ava-core = { workspace = true }
ava-extension-api = { workspace = true }
ava-otel = { workspace = true }
ava-protocol = { workspace = true }
ava-tools = { workspace = true }
ava-utils-absolute-path = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
which = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
