[package]
edition.workspace = true
license.workspace = true
name = "ava-git-attribution"
version.workspace = true

[lib]
name = "ava_git_attribution"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
ava-backend-client = { workspace = true }
ava-extension-api = { workspace = true }
ava-http-client = { workspace = true }
ava-login = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
