[package]
edition.workspace = true
license.workspace = true
name = "ava-analytics"
version.workspace = true

[lib]
doctest = false
name = "ava_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ava-app-server-protocol = { workspace = true }
ava-git-utils = { workspace = true }
ava-login = { workspace = true }
ava-model-provider = { workspace = true }
ava-plugin = { workspace = true }
ava-protocol = { workspace = true }
ava-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
ava-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
