[package]
name = "ava-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ava_arg0"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
ava-apply-patch = { workspace = true }
ava-async-utils = { workspace = true }
ava-exec-server = { workspace = true }
ava-install-context = { workspace = true }
ava-linux-sandbox = { workspace = true }
ava-sandboxing = { workspace = true }
ava-shell-escalation = { workspace = true }
ava-utils-absolute-path = { workspace = true }
ava-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
ava-windows-sandbox = { workspace = true }
pathdiff = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
