[package]
name = "ava-utils-oss"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ava-core = { workspace = true }
ava-lmstudio = { workspace = true }
ava-model-provider-info = { workspace = true }
ava-ollama = { workspace = true }

[lib]
doctest = false
