[package]
edition.workspace = true
license.workspace = true
name = "ava-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
ava-protocol = { workspace = true }
ava-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
