[package]
name = "ava-app-server-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ava_app_server_client"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
ava-app-server = { workspace = true }
ava-app-server-protocol = { workspace = true }
ava-arg0 = { workspace = true }
ava-config = { workspace = true }
ava-core = { workspace = true }
ava-exec-server = { workspace = true }
ava-feedback = { workspace = true }
ava-protocol = { workspace = true }
ava-uds = { workspace = true }
ava-utils-absolute-path = { workspace = true }
ava-utils-rustls-provider = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "rt"] }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
